kind: pipeline
name: default

steps:
- name: main
  image: golang
  commands:
  - go test

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: notifications
